# fly.toml app configuration file generated for eipf-site-nginx on 2025-04-26T17:11:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eipf-site-nginx'
primary_region = 'ams'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
