# Generated by Django 5.1.7 on 2025-03-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('private_key', models.CharField(max_length=60, null=True)),
                ('iban', models.CharField(max_length=35, null=True)),
                ('withdraw', models.BooleanField(default=False, null=True)),
                ('insurance', models.BooleanField(default=False, null=True)),
                ('permisiion', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.manager')),
                ('payments_division_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.paymentsdivisionmanager')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
