# Generated by Django 5.1.7 on 2025-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_customuser_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='permisiion',
            new_name='permissions',
        ),
    ]
