# Generated by Django 5.1.7 on 2025-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_rename_permisiion_customuser_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permissions',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='User', max_length=10),
        ),
    ]
