# Generated by Django 5.1.7 on 2025-04-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0004_alter_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('replenishment', 'Replenishment')], max_length=20),
        ),
    ]
