# Generated by Django 5.1.7 on 2025-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_alter_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('replenishment', 'Replenishment'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
