# Generated by Django 5.1.7 on 2025-04-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_alter_transfer_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='amount',
            new_name='ammount',
        ),
    ]
